default_stages: [pre-commit, pre-push]
fail_fast: false
exclude: ^othello/(static/.*vendor|.*migrations)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
        name: validate python
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-toml
      - id: detect-private-key
      - id: check-yaml
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        files: ^.*\.(py|md|rst)$
        args: ["--ignore-words=.codespell-ignore.txt"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
      - id: ruff
        args: [ "--fix", "--exit-non-zero-on-fix" ]
        files: ^othello/.*
        name: ruff lint
      - id: ruff-format
